### ISSUE TITLE
[Question] Would you support less too?

### ISSUE THREAD

**Issue by dzcpy** [Thream/styled-jsx-plugin-sass#11]
### Question
Thanks for making this awesome library. Is there any chance that you would be interested working on a `@styled-jsx/plugin-less` module? I know not many people use less, but for projects which use `antd`, `less` is still somehow needed. There is already one https://github.com/erasmo-marin/styled-jsx-plugin-less but when I tried it, it doesn't work.

**Comment by Divlo** [comment]
Hey @dzcpy  👋,

This package is about supporting `sass` with `styled-jsx`, so there is no plan to support `less`, please open a issue in https://github.com/erasmo-marin/styled-jsx-plugin-less.
Or maybe you could fork the repo, and try to maintain a plugin to support `less` with `styled-jsx` yourself.
