### ISSUE TITLE
[Bug] ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by elliotreborn** [Thream/styled-jsx-plugin-sass#68]
## Steps To Reproduce
```
npx create-next-app --ts app
cd app
npm install --save-dev sass @styled-jsx/plugin-sass
```
add babel.config.json:
```json
{
  "presets": [
    [
      "next/babel",
      {
        "styled-jsx": {
          "plugins": ["@styled-jsx/plugin-sass"]
        }
      }
    ]
  ]
}
```

## The current behavior

$ npm run dev

> next-start@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Using external babel configuration from babel.config.json
[styled-jsx] Loading plugin from path: node_modules\@styled-jsx\plugin-sass\index.js
info  - Using external babel configuration from babel.config.json
info  - Using external babel configuration from babel.config.json
info  - Using external babel configuration from babel.config.json
error - ./node_modules/next/dist/client/next-dev.js
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: node_modules\@styled-jsx\plugin-sass\index.js
require() of ES modules is not supported.
require() of node_modules\@styled-jsx\plugin-sass\index.js from node_modules\styled-jsx\dist\_utils.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from node_modules\@styled-jsx\plugin-sass\package.json.
    at Array.map (<anonymous>)
<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|node_modules\@next\react-refresh-utils\loader.js!node_modules\next\dist\build\babel\loader\index.js??ruleSet[1].rules[1].use[1]!node_modules\next\dist\client\next-dev.js': No serializer registered for NodeError
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> webpack/lib/ModuleBuildError -> NodeError
info  - Using external babel configuration from babel.config.json

**Comment by Divlo** [comment]
Thanks for your report! @elliotreborn 

Indeed, it is a bug, good catch!
I don't know why it worked before `next@11.1.O`.
The problematic line of code is: https://github.com/vercel/styled-jsx/blob/e41c6fe488b7c25ddc2a8033106f1df424986ccc/src/_utils.js#L530

I opened a PR to fix this on `styled-jsx`: https://github.com/vercel/styled-jsx/pull/732 :smile:
